### ISSUE TITLE
Click on upload button,my application has been crashed

### ISSUE THREAD

**Issue by Sunaina015** [zendesk/connect-android-sdk#15]
01-04 18:29:27.850 27954-27954/w3bminds.engVarta.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: w3bminds.engVarta.app, PID: 27954
    java.lang.NoSuchMethodError: No static method with(Landroid/content/Context;)Lcom/squareup/picasso/Picasso; in class Lcom/squareup/picasso/Picasso; or its super classes (declaration of 'com.squareup.picasso.Picasso' appears in /data/app/w3bminds.engVarta.app-2/split_lib_dependencies_apk.apk:classes2.dex)
        at zendesk.belvedere.ImageStreamItems$StreamItemImage.bind(ImageStreamItems.java:178)
        at zendesk.belvedere.ImageStreamAdapter.onBindViewHolder(ImageStreamAdapter.java:36)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
        at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1613)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:687)
        at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:609)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16672)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16672)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
        at android.support.design.widget.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:222)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:16672)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16672)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16672)
        at android.view.ViewGroup.layout(ViewGroup.java:5438)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1144)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6102)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
        at android.view.Choreographer.doCallbacks(Choreographer.java:672)
        at android.view.Choreographer.doFrame(Choreographer.java:608)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by danthedrummer** [comment]
Hi,

Apologies for the delay but I wasn't receiving notifications for this repo. 

The Connect SDK doesn't use Picasso and doesn't appear on the dependency tree so I can't help you here.

**Comment by lauramdelarosa** [comment]
@Sunaina015 did you solve the problem? this error is in my app and has a lot of crashes.

**Comment by lauramdelarosa** [comment]
I solved updating zendesk version to 3.0.2
