### ISSUE TITLE
[ANR] Reported within the Zendesk component

### ISSUE THREAD

**Issue by raghav2945** [zendesk/connect-android-sdk#19]
We are very pleased with the capabilities of your library, but we have recently begun receiving a number of ANR from your component. These issues have been reported via Firebase, and we attempted but failed to reproduce them locally. Sharing the top four most common ANR stack-traces with the highest frequency of occurrence.

### Stack-trace

**1. zendesk.core.GsonSerializer.serialize**
```
main (runnable): tid=1 systid=2696
       at java.lang.String.toLowerCase(String.java:2666)
       at com.google.gson.FieldNamingPolicy$4.translateName(FieldNamingPolicy.java:92)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldNames(ReflectiveTypeAdapterFactory.java:76)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
       at com.google.gson.Gson.getAdapter(Gson.java:458)
       at com.google.gson.Gson.toJson(Gson.java:696)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at zendesk.core.GsonSerializer.serialize(GsonSerializer.java:71)
       at zendesk.core.SharedPreferencesStorage.put(SharedPreferencesStorage.java:39)
       at zendesk.core.ZendeskPushDeviceIdStorage.storePushRegistrationRequest(ZendeskPushDeviceIdStorage.java:40)
       at zendesk.core.ZendeskPushRegistrationProvider.storePendingPushRegistrationRequest(ZendeskPushRegistrationProvider.java:98)
       at zendesk.core.ZendeskPushRegistrationProvider.access$300(ZendeskPushRegistrationProvider.java:21)
       at zendesk.core.ZendeskPushRegistrationProvider$1.onSuccess(ZendeskPushRegistrationProvider.java:84)
       at zendesk.core.ZendeskPushRegistrationProvider$1.onSuccess(ZendeskPushRegistrationProvider.java:68)
       at zendesk.core.ZendeskSettingsProvider$1.onSuccess(ZendeskSettingsProvider.java:86)
       at zendesk.core.ZendeskSettingsProvider$1.onSuccess(ZendeskSettingsProvider.java:79)
       at com.zendesk.service.RetrofitZendeskCallbackAdapter.onResponse(RetrofitZendeskCallbackAdapter.java:67)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
       at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7700)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```
**2. zendesk.core.GsonSerializer.deserialize**
```
main (runnable): tid=1 systid=4137
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1321)
       at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1570)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:533)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
       at com.google.gson.Gson.fromJson(Gson.java:928)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at zendesk.core.GsonSerializer.deserialize(GsonSerializer.java:46)
       at zendesk.core.SharedPreferencesStorage.get(SharedPreferencesStorage.java:55)
       at zendesk.core.ZendeskSettingsStorage.getSettings(ZendeskSettingsStorage.java:34)
       at zendesk.core.ZendeskCoreSettingsStorage.getBlipsSettings(ZendeskCoreSettingsStorage.java:49)
       at zendesk.core.ZendeskBlipsProvider.sendBlip(ZendeskBlipsProvider.java:77)
       at zendesk.core.ZendeskBlipsProvider.sendBlip(ZendeskBlipsProvider.java:61)
       at zendesk.core.ZendeskBlipsProvider.coreInitialized(ZendeskBlipsProvider.java:103)
       at zendesk.core.ZendeskShadow.init(ZendeskShadow.java:53)
       at zendesk.core.Zendesk.init(Zendesk.java:82)
       at zendesk.core.Zendesk.init(Zendesk.java:66)
       at com.audiomack.data.support.ZendeskRepository.ensureInitialized(ZendeskRepository.kt:172)
       at com.audiomack.data.support.ZendeskRepository.trackIdentity(ZendeskRepository.kt:127)
       at com.audiomack.data.support.ZendeskRepository.registerForPush(ZendeskRepository.kt:142)
       at com.audiomack.data.support.ZendeskDataSource$DefaultImpls.registerForPush$default(ZendeskDataSource.kt:19)
       at com.audiomack.data.support.ZendeskRepository.<init>(ZendeskRepository.kt:48)
       at com.audiomack.data.support.ZendeskRepository$Companion.init(ZendeskRepository.kt:220)
       at com.audiomack.data.support.ZendeskRepository$Companion.init$default(ZendeskRepository.kt:209)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:8)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:7)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8152)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7688)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7508)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2158)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
**3. zendesk.core.ZendeskStorageModule.getSharedPrefs**
```
main (native): tid=1 systid=30750
#00 pc 0xa0b1c libc.so 
#01 pc 0xb035b libc.so 
#02 pc 0x423ffd libart.so 
       at java.lang.Thread.nativeCreate(Native method)
       at java.lang.Thread.start(Thread.java:887)
       at android.app.SharedPreferencesImpl.startLoadFromDisk(SharedPreferencesImpl.java:142)
       at android.app.SharedPreferencesImpl.<init>(SharedPreferencesImpl.java:130)
       at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:535)
       at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:506)
       at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:198)
       at zendesk.core.ZendeskStorageModule.getSharedPrefs(ZendeskStorageModule.java:247)
       at zendesk.core.ZendeskStorageModule.provideSettingsBaseStorage(ZendeskStorageModule.java:130)
       at zendesk.core.ZendeskStorageModule_ProvideSettingsBaseStorageFactory.provideSettingsBaseStorage(ZendeskStorageModule_ProvideSettingsBaseStorageFactory.java:35)
       at zendesk.core.ZendeskStorageModule_ProvideSettingsBaseStorageFactory.get(ZendeskStorageModule_ProvideSettingsBaseStorageFactory.java:26)
       at zendesk.core.ZendeskStorageModule_ProvideSettingsBaseStorageFactory.get(ZendeskStorageModule_ProvideSettingsBaseStorageFactory.java:9)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.core.ZendeskStorageModule_ProvideSettingsStorageFactory.get(ZendeskStorageModule_ProvideSettingsStorageFactory.java:22)
       at zendesk.core.ZendeskStorageModule_ProvideSettingsStorageFactory.get(ZendeskStorageModule_ProvideSettingsStorageFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.core.ZendeskStorageModule_ProvideSdkStorageFactory.get(ZendeskStorageModule_ProvideSdkStorageFactory.java:33)
       at zendesk.core.ZendeskStorageModule_ProvideSdkStorageFactory.get(ZendeskStorageModule_ProvideSdkStorageFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.core.ZendeskApplicationModule_ProvideZendeskFactory.get(ZendeskApplicationModule_ProvideZendeskFactory.java:44)
       at zendesk.core.ZendeskApplicationModule_ProvideZendeskFactory.get(ZendeskApplicationModule_ProvideZendeskFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.core.DaggerZendeskApplicationComponent.zendeskShadow(DaggerZendeskApplicationComponent.java:251)
       at zendesk.core.Zendesk.init(Zendesk.java:81)
       at zendesk.core.Zendesk.init(Zendesk.java:66)
       at com.audiomack.data.support.ZendeskRepository.ensureInitialized(ZendeskRepository.kt:172)
       at com.audiomack.data.support.ZendeskRepository.trackIdentity(ZendeskRepository.kt:127)
       at com.audiomack.data.support.ZendeskRepository.registerForPush(ZendeskRepository.kt:142)
       at com.audiomack.data.support.ZendeskDataSource$DefaultImpls.registerForPush$default(ZendeskDataSource.kt:19)
       at com.audiomack.data.support.ZendeskRepository.<init>(ZendeskRepository.kt:48)
       at com.audiomack.data.support.ZendeskRepository$Companion.init(ZendeskRepository.kt:220)
       at com.audiomack.data.support.ZendeskRepository$Companion.init$default(ZendeskRepository.kt:209)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:8)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:7)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8190)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7726)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7546)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
**4. zendesk.support.ZendeskRequestStorage.<clinit>**
```
main (runnable): tid=1 systid=15308
       at java.lang.StringBuilder.<init>(StringBuilder.java:90)
       at android.icu.impl.ICUResourceBundleReader.getStringV2(ICUResourceBundleReader.java:522)
       at android.icu.impl.ICUResourceBundleReader.getString(ICUResourceBundleReader.java:575)
       at android.icu.impl.ICUResourceBundleReader$ReaderValue.getString(ICUResourceBundleReader.java:815)
       at android.icu.impl.ICUCurrencyDisplayInfoProvider$ICUCurrencyDisplayInfo$CurrencySink.consumeCurrenciesEntry(ICUCurrencyDisplayInfoProvider.java:456)
       at android.icu.impl.ICUCurrencyDisplayInfoProvider$ICUCurrencyDisplayInfo$CurrencySink.put(ICUCurrencyDisplayInfoProvider.java:373)
       at android.icu.impl.ICUResourceBundle.getAllItemsWithFallback(ICUResourceBundle.java:448)
       at android.icu.impl.ICUResourceBundle.getAllItemsWithFallback(ICUResourceBundle.java:429)
       at android.icu.impl.ICUResourceBundle.getAllItemsWithFallbackNoFail(ICUResourceBundle.java:400)
       at android.icu.impl.ICUCurrencyDisplayInfoProvider$ICUCurrencyDisplayInfo.fetchFormattingData(ICUCurrencyDisplayInfoProvider.java:257)
       at android.icu.impl.ICUCurrencyDisplayInfoProvider$ICUCurrencyDisplayInfo.getSymbol(ICUCurrencyDisplayInfoProvider.java:163)
       at android.icu.util.Currency.getName(Currency.java:545)
       at android.icu.util.Currency.getSymbol(Currency.java:489)
       at android.icu.util.Currency.getSymbol(Currency.java:479)
       at android.icu.text.DecimalFormatSymbols.setCurrency(DecimalFormatSymbols.java:826)
       at java.text.DecimalFormatSymbols.getIcuDecimalFormatSymbols(DecimalFormatSymbols.java:806)
       at java.text.DecimalFormat.initPattern(DecimalFormat.java:491)
       at java.text.DecimalFormat.<init>(DecimalFormat.java:481)
       at java.text.NumberFormat.getInstance(NumberFormat.java:848)
       at java.text.NumberFormat.getIntegerInstance(NumberFormat.java:498)
       at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:725)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:691)
       at zendesk.support.ZendeskRequestStorage.<clinit>(ZendeskRequestStorage.java:24)
       at zendesk.support.StorageModule.provideRequestStorage(StorageModule.java:26)
       at zendesk.support.StorageModule_ProvideRequestStorageFactory.provideRequestStorage(StorageModule_ProvideRequestStorageFactory.java:47)
       at zendesk.support.StorageModule_ProvideRequestStorageFactory.get(StorageModule_ProvideRequestStorageFactory.java:35)
       at zendesk.support.StorageModule_ProvideRequestStorageFactory.get(StorageModule_ProvideRequestStorageFactory.java:10)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.support.ProviderModule_ProvideRequestProviderFactory.get(ProviderModule_ProvideRequestProviderFactory.java:54)
       at zendesk.support.ProviderModule_ProvideRequestProviderFactory.get(ProviderModule_ProvideRequestProviderFactory.java:9)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.support.ProviderModule_ProvideProviderStoreFactory.get(ProviderModule_ProvideProviderStoreFactory.java:32)
       at zendesk.support.ProviderModule_ProvideProviderStoreFactory.get(ProviderModule_ProvideProviderStoreFactory.java:8)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at zendesk.support.DaggerSupportSdkProvidersComponent.injectSupport(DaggerSupportSdkProvidersComponent.java:133)
       at zendesk.support.DaggerSupportSdkProvidersComponent.inject(DaggerSupportSdkProvidersComponent.java:130)
       at zendesk.support.Support.initApplicationScope(Support.java:191)
       at zendesk.support.Support.init(Support.java:71)
       at com.audiomack.data.support.ZendeskRepository.ensureInitialized(ZendeskRepository.kt:181)
       at com.audiomack.data.support.ZendeskRepository.trackIdentity(ZendeskRepository.kt:127)
       at com.audiomack.data.support.ZendeskRepository.registerForPush(ZendeskRepository.kt:142)
       at com.audiomack.data.support.ZendeskDataSource$DefaultImpls.registerForPush$default(ZendeskDataSource.kt:19)
       at com.audiomack.data.support.ZendeskRepository.<init>(ZendeskRepository.kt:48)
       at com.audiomack.data.support.ZendeskRepository$Companion.init(ZendeskRepository.kt:220)
       at com.audiomack.data.support.ZendeskRepository$Companion.init$default(ZendeskRepository.kt:209)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:8)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:7)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8190)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7726)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7546)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by raghav2945** [comment]
We're closing this because we're handling it via email and the Zendesk support channel.
